---
title: "SBW Project Outline"
output: html_notebook
---

The dataset we’re using for this project consists of daily observations of lab-reared spruce budworm larvae. Throughout their lifespan, these insects progress through distinct larval stages. The purpose of the lab experiment is to model how temperature affects how the insects develop, and differences in development across different populations. Five colonies of insects were collected from across the country, along with a colony that has been lab-reared for many generations. Seven different constant-temperature regimes were performed on each colony, from 5-35 degrees Celsius in 5-degree increments. The first portion of the project will focus on the rate of development of the budworm as it moves through its life stages, and how temperature and origin affect rates of individuals. The second portion will focus on model fitting, and the third portion will summarize simulation results from the model using real temperature data from one location over several years.

The first component of the visualization project is a shiny animation. We want to demonstrate the movement of spruce budworm larvae across multiple life stages. The graphic, which would contain the larval stages on the x-axis, and the individual larvae on the y-axis, similar to a “starting line”, would show the transition of the larvae through their respective stages over time using animation. The graphic’s animation will show the population moving from one stage to another via point movement with points that change colour for each larval stage. When an individual dies, it will be shown as a translucent data point on the graph. This shiny application will have toggles that allow the user to view the animation of the data for a selected colony and treatment temperature using checkbox selectors. The user will also be able to toggle through time in days using a slider at the bottom.  

The data will be fitted to a development model specific to the spruce budworm, created by Regniere and St.-Amant (2012). The model consists of temperature-dependent development rate curves, coupled with variability curves that are symmetric around the median development rate for each larval instar. The development rate curve is a non-linear function of temperature with four parameters that we’ll fit using nlme. The temperature values used as inputs are adjusted based on upper and lower development thresholds, for which we’ll use the published values. It is assumed in the model that within a given larval stage, development occurs linearly over a given time step based on temperature. An insect’s development rate for a larval stage is equivalent to the reciprocal of the time it took to complete that stage; the “age” of an insect in a stage is the proportion the stage it’s completed. The CDFs of the variability densities are two-parameter sigmoidal curves that are fit to the ratios of each individual’s development rate to the median for the population. This acts as the distribution of the deviation of an individual from the median development rate curve. It is assumed that for each stage, the distribution of deviation from the curve is the same for any temperature. It is also assumed that there is no correlation in relative development speed for an individual insect across larval stages. The plots that will be used to represent this modelling aspect will include the fitted development rate curves, perhaps with density envelopes around the curve that show individuals’ expected deviation, faceted by colony. Overlayed on this will be the points representing each data point (insect), jittered to show where most of the insects lie relative to the curve. Another plot will show the development curves for each colony in the same plot for direct comparison.

The final graphic will be a stacked density plot showing the proportion of insects in each larval stage over a year using a population simulated from the model fitted above. The population will be simulated using historical weather data for a certain region as an input. This will show how a population is expected to progress through its larval stages over time, based on the temperatures experienced in a given year. There will be a slider that will allow the viewer to toggle across years to see how the development changes over time. Another goal of the graphic is to implement an interactive aspect using plotly that will have a vertical line with a tooltip specifying the proportion of larvae in each stage on a given day. Since the model does not have a survival component, deaths will not be included in the graphic. Another aspect of this graphic that might be needed is a way to compare temperatures across years, such as a trendline; this will help to inform the behaviour of the simulated population seen in the stacked density graphic. This would likely need to be a separate plot.

Overall, the graphics presented will give the user an understanding of the development process of the spruce budworm and how this is affected by temperature and insect origin. 

References
Régnière, Jacques, Rémi St-Amant, and Pierre Duval. "Predicting insect distributions under climate change from physiological responses: spruce budworm as an example." Biological Invasions 14.8 (2012): 1571-1586.
